### PR TITLE
julia >=0.7 support

### PR DESCRIPTION
**Pull request by amanica**
Hi, 
I've done some work to make it support julia 0.7 and 1.0.3 (all tests pass on those) and use the new package management.
Selection_008

Next I'm keen to make it work a little more like java:
* see if I can get the dot operator to work so one can call object methods like this: `myObject.someMethod()`
* see if I can get it to inject a `this` parameter for methods rather than having to declare `self` everywhere
  * for cases where one don't want it, declare it outside the function or add `@static` macro

### CODE REVIEW

**Comment by ipod825** [comment]
Thanks for your work.

Two questions:
1. Are the files test/Manifest.toml, test/Project.toml necessary?
2. Why do we need to put the code in OOPMacro.jl into OOPMacroImpl.jl?

**Comment by amanica** [comment]
> Thanks for your work.

my pleasure, thanks for the quick response :)

> 1. Are the files test/Manifest.toml, test/Project.toml necessary?

Good question, it was my attempt to have a test-only dependency.
I removed that and fixed the main files according to:  https://docs.julialang.org/en/v1.0/stdlib/Pkg/#Test-specific-dependencies-1

> 2. Why do we need to put the code in OOPMacro.jl into OOPMacroImpl.jl?

The main reason is to make it easier to develop and test: if I update something I just run the OOPMacroImpl.jl file and then the test file. In this way it runs without putting it into a module which I find much easier to work with.

What do you think of my other ideas that I'm keen to work on next?

**Comment by ipod825** [comment]
> see if I can get the dot operator to work so one can call object methods like this: myObject.someMethod()

This is definitely desirable, though I didn't figure out a clever way of doing it. I had thought:
1. Maintain a function map and overload the dot operation. But that should cause much runtime overhead in both memory and runtime.
2. Introduce yet another macro like "@fncall obj.method(arrg)", but this is not very practical.

> see if I can get it to inject a this parameter for methods rather than having to declare self everywhere
for cases where one don't want it, declare it outside the function or add @static macro

I personly prefer the python style better. Explicit makes programmer know whether the variable in question is a local variable or an instance variable. I would always add "this" when I am referring to an instance variable. But I believe that there should be programmers that are used to this syntax sugar and would want it. So if you want to implement this, please go ahead.

**Comment by ipod825** [comment]
Also, I'll merge your commit in this thread. Further improvements should rest in other threads.

**Comment by ipod825** [comment]
@JuliaRegistrator register()

**Comment by amanica** [comment]
> Also, I'll merge your commit in this thread. 

Awesome, thanks.
Well done on getting the pacakge registered! :) https://juliaobserver.com/packages/OOPMacro

> Further improvements should rest in other threads.

of coarse, I'll do that :)

**Pull request merged**
